# install.packages(c("mc2d","devtools", "MASS", "pwr", "truncnorm", "truncdist", "dplyr", "data.table", "foreach", "doMC", "meta", "progress", "doMC", "reshape2", "metafor", "notifyR", "broom", "weightr", "doParallel", "gtools", "weightr", "rio", "gridExtra", "invgamma"))
library(MASS)
library(pwr)
library(compiler)
library(truncnorm)
library(truncdist)
library(reshape2)
library(dplyr)
library(data.table)
library(foreach)
#library(doMC)
library(meta)
library(metafor)
library(progress)
library(notifyR)
library(broom)
# library(puniform)
library(weightr)
library(stats)
